Repository boostcampwm-2024/web01-youQuiz, pull requests merged in 2024-12, with the labels that each got.

#146 [BE -#145] shared 패키지의 상수 사용을 위한 server 설정
  .pnp.cjs
  .yarn/cache/array-union-npm-2.1.0-4e4852b221-429897e681.zip
  .yarn/cache/commander-npm-9.5.0-993b3f2434-5f7784fbda.zip
  .yarn/cache/dir-glob-npm-3.0.1-1aea628b1b-dcac00920a.zip
  .yarn/cache/globby-npm-11.1.0-bdcdf20c71-b39511b4af.zip
  .yarn/cache/mylas-npm-2.1.13-9120e6f561-093dfaf88f.zip
  .yarn/cache/plimit-lit-npm-1.6.1-3a51cebb9f-af5d351bb5.zip
  .yarn/cache/queue-lit-npm-1.5.2-a2de1bdaad-8aa838b2c9.zip
  .yarn/cache/tsc-alias-npm-1.8.10-a746925ff7-6f319d37b3.zip
  packages/server/package.json
  yarn.lock
Labels: 👷 Build

#147 [BE - #148] - 리더보드 이벤트 추가 및 코드 리팩토링
  packages/server/src/config/database/redis/redis.service.ts
  packages/server/src/module/game/games/dto/request/emoji.request.dto.ts
  packages/server/src/module/game/games/dto/request/end-quiz.request.dto.ts
  packages/server/src/module/game/games/dto/request/leaderboard.request.dto.ts
  packages/server/src/module/game/games/dto/request/master-entry.request.dto.ts
  packages/server/src/module/game/games/dto/request/message.request.dto.ts
  packages/server/src/module/game/games/dto/request/nickname.request.dto.ts
  packages/server/src/module/game/games/dto/request/participant-entry.request.dto.ts
  packages/server/src/module/game/games/dto/request/show-quiz.request.dto.ts
  packages/server/src/module/game/games/dto/request/show-ranking.request.dto.ts
  packages/server/src/module/game/games/dto/request/start-quiz.request.dto.ts
  packages/server/src/module/game/games/dto/request/submit-answer.request.dto.ts
  packages/server/src/module/game/games/game.gateway.ts
  packages/server/src/module/game/games/game.service.ts
  packages/shared/constants/b.ts
  packages/shared/constants/game.constants.ts
  packages/shared/constants/utils.constants.ts
  packages/shared/interfaces/request/emoji.request.interface.ts
  packages/shared/interfaces/request/end-quiz.request.interface.ts
  packages/shared/interfaces/request/leaderboard.request.interface.ts
  packages/shared/interfaces/request/message.request.interface.ts
  packages/shared/interfaces/request/show-ranking.interface.ts
  packages/shared/interfaces/request/submit-answer.request.interface.ts
Labels: ✨ Feature, 🤖 Refactor

#149 [FE] - 리더보드 UI 구현 및 useQuery + emitAckEvent Wrapper 함수 구현
  .pnp.cjs
  .yarn/cache/@tanstack-query-devtools-npm-5.61.4-757435dc28-44886dbf92.zip
  .yarn/cache/@tanstack-react-query-devtools-npm-5.62.0-c120ddf122-b5f94368d8.zip
  packages/client/package.json
  packages/client/src/app/routes/Router.tsx
  packages/client/src/main.tsx
  packages/client/src/pages/leaderboard/ConfettiBackground.tsx
  packages/client/src/pages/leaderboard/PlayerList.tsx
  packages/client/src/pages/leaderboard/TopPlayer.tsx
  packages/client/src/pages/leaderboard/index.tsx
  packages/client/src/pages/leaderboard/model/hooks/useLeaderboard.ts
  packages/client/src/pages/quiz-master-session/index.tsx
  packages/client/src/pages/quiz-session/index.tsx
  packages/client/src/shared/utils/emitEventWithAck.ts
  packages/client/tailwind.config.js
  yarn.lock
Labels: ✨ Feature

#150 [FE] - 마스터 그래프 페이지 버그 해결
  packages/client/index.html
  packages/client/src/index.css
  packages/client/src/pages/quiz-list/ui/ClassItem.tsx
  packages/client/src/pages/quiz-master-session/index.tsx
  packages/client/src/pages/quiz-master-session/ui/AnswerChart.tsx
  packages/client/src/pages/quiz-master-session/ui/EmojiChart.tsx
  packages/client/src/pages/quiz-master-session/ui/RecentSubmittedAnswers.tsx
  packages/client/src/pages/quiz-wait/ui/UserGridItem.tsx
  packages/client/src/shared/constants/initialState.ts
  packages/client/src/shared/utils/formatElapsedTime.ts
Labels: 🛠️ Fix

#154 [BE - #153] 게임 참여 인원 체크 API 구현 및 participant entry 이벤트 분리
  packages/server/src/module/game/games/game.controller.ts
  packages/server/src/module/game/games/game.gateway.ts
  packages/server/src/module/game/games/game.service.ts
Labels: ✨ Feature, 🤖 Refactor

#155 [FE] - Session, Quiz-wait 페이지 이벤트 로직 변경
  packages/client/src/app/routes/Router.tsx
  packages/client/src/pages/main/index.tsx
  packages/client/src/pages/nickname/index.tsx
  packages/client/src/pages/quiz-wait/index.lazy.tsx
  packages/client/src/pages/quiz-wait/index.tsx
  packages/client/src/pages/quiz-wait/model/hooks/useNickname.ts
  packages/client/src/pages/quiz-wait/ui/UserGridItem.tsx
  packages/client/src/pages/quiz-wait/ui/UserGridView.tsx
  packages/client/src/shared/api/games/index.ts
Labels: 🤖 Refactor

#156 [FE] - 마스터 채팅 기능 추가
  packages/client/src/app/layouts/GuestLayout.tsx
  packages/client/src/app/layouts/HostLayout.tsx
  packages/client/src/pages/quiz-wait/ui/MasterChat.tsx
  packages/client/src/pages/quiz-wait/ui/UserGridItem.tsx
  packages/client/src/pages/quiz-wait/ui/UserGridView.tsx
  packages/client/src/shared/ui/header/Header.tsx
Labels: ✨ Feature

#157 [FE] - 마스터, 참가자 퀴즈 세션 새로고침 반영
  packages/client/src/pages/quiz-master-session/index.lazy.tsx
  packages/client/src/pages/quiz-master-session/index.tsx
  packages/client/src/pages/quiz-master-session/ui/AnswerChart.tsx
  packages/client/src/pages/quiz-master-session/ui/QuizMasterHeader.tsx
  packages/client/src/pages/quiz-master-session/ui/Statistics.tsx
  packages/client/src/pages/quiz-session/index.lazy.tsx
  packages/client/src/pages/quiz-session/index.tsx
  packages/client/src/pages/quiz-session/model/hooks/useQuizSession.ts
  packages/client/src/pages/quiz-session/model/hooks/useShowRanking.ts
  packages/client/src/pages/quiz-session/ui/QuizBox.tsx
  packages/client/src/pages/quiz-session/ui/QuizEnd.tsx
  packages/client/src/pages/quiz-session/ui/QuizHeader.tsx
  packages/client/src/pages/quiz-wait/index.lazy.tsx
  packages/client/src/shared/hooks/usePersistState.ts
  packages/client/src/shared/utils/clearLocalStorage.ts
  packages/client/src/shared/utils/emitEventWithDelay.ts
  packages/server/src/module/game/games/game.gateway.ts
Labels: 🤖 Refactor

#158 [BE] 소켓 서버 관련 가드 설정 및 API 구현
  packages/server/src/config/database/redis/redis.service.ts
  packages/server/src/module/game/games/game.gateway.ts
  packages/server/src/module/guards/session.guard.ts
  packages/server/src/module/quiz/quizzes/quiz.service.ts
  packages/server/src/module/quiz/quizzes/repositories/class.repository.ts
  packages/shared/types/gameStatus.types.ts
Labels: ✨ Feature

#159 [FE] - 퀴즈 리스트 페이지 에러 해결
  packages/client/src/pages/quiz-create/index.tsx
  packages/client/src/pages/quiz-list/index.lazy.tsx
  packages/client/src/pages/quiz-list/ui/ClassItem.tsx
  packages/client/src/pages/quiz-list/ui/EmptyClassList.tsx
  packages/client/src/shared/hooks/classes.ts
  packages/client/src/shared/hooks/quizzes.ts
  packages/client/src/shared/ui/buttons/CustomButton.tsx
Labels: 🛠️ Fix, ✨ Feature

#160 [BE] - 게임 상태 가져오는 API 구현
  packages/server/src/module/game/games/game.controller.ts
  packages/server/src/module/game/games/game.service.ts
Labels: ✨ Feature

#161 [BE -#162 ] 클래스 삭제 API: 벌크 삭제로 변경
  packages/server/src/module/quiz/quizzes/entities/choice.entity.ts
  packages/server/src/module/quiz/quizzes/quiz.service.ts
  packages/server/src/module/quiz/quizzes/repositories/class.repository.ts
Labels: 🤖 Refactor

#163 [FE] - 퀴즈 진행 관련 에러 해결
  packages/client/src/app/routes/Router.tsx
  packages/client/src/pages/leaderboard/index.tsx
  packages/client/src/pages/main/index.tsx
  packages/client/src/pages/quiz-list/ui/ClassItem.tsx
  packages/client/src/pages/quiz-master-session/index.lazy.tsx
  packages/client/src/pages/quiz-master-session/ui/AnswerChart.tsx
  packages/client/src/pages/quiz-master-session/ui/Statistics.tsx
  packages/client/src/pages/quiz-session/index.lazy.tsx
  packages/client/src/pages/quiz-session/model/hooks/useGetMyInfo.ts
  packages/client/src/pages/quiz-session/model/hooks/useQuizSession.ts
  packages/client/src/pages/quiz-session/ui/ProgressBar.tsx
  packages/client/src/pages/quiz-session/ui/QuizBox.tsx
  packages/client/src/pages/quiz-session/ui/QuizEnd.tsx
  packages/client/src/pages/quiz-session/ui/QuizHeader.tsx
  packages/client/src/pages/quiz-session/ui/QuizLoading.tsx
  packages/client/src/shared/api/games/index.ts
  packages/client/src/shared/boundary/AsyncBoundary.tsx
  packages/client/src/shared/utils/cookie.ts
  packages/server/src/module/game/games/game.gateway.ts
Labels: 🛠️ Fix, ✨ Feature

#164 [FE] - 퀴즈 랭킹 에러 수정
  packages/client/src/pages/quiz-master-session/ui/RecentSubmittedAnswers.tsx
  packages/client/src/pages/quiz-master-session/ui/Statistics.tsx
  packages/client/src/pages/quiz-session/index.lazy.tsx
  packages/client/src/pages/quiz-session/ui/QuizEnd.tsx
  packages/client/src/pages/quiz-session/ui/QuizHeader.tsx
  packages/client/src/pages/quiz-wait/index.lazy.tsx
  packages/client/src/shared/ui/header/Header.tsx
Labels: 🛠️ Fix

#165 [FE] - 에러 바운더리, 프로그레스바 추가
  .pnp.cjs
  .yarn/cache/react-error-boundary-npm-4.1.2-7591172537-0737e5259b.zip
  packages/client/package.json
  packages/client/src/pages/quiz-session/index.lazy.tsx
  packages/client/src/pages/quiz-session/ui/ProgressBar.tsx
  packages/client/src/pages/quiz-session/ui/QuizHeader.tsx
  packages/client/src/shared/boundary/AsyncBoundary.tsx
  yarn.lock
Labels: ✨ Feature

#167 [BE -#166] 벌크 삽입으로 리팩토링
  packages/server/src/module/quiz/quizzes/quiz.controller.ts
  packages/server/src/module/quiz/quizzes/quiz.service.ts
  packages/server/src/module/quiz/quizzes/repositories/choice.repository.ts
  packages/server/src/module/quiz/quizzes/repositories/class.repository.ts
  packages/server/src/module/quiz/quizzes/repositories/quiz.repository.ts
Labels: 🤖 Refactor

#169 [BE -#168] 벌크 삭제 로직 책임 분리
  packages/server/src/module/quiz/quizzes/entities/quiz.entity.ts
  packages/server/src/module/quiz/quizzes/quiz.service.ts
  packages/server/src/module/quiz/quizzes/repositories/choice.repository.ts
  packages/server/src/module/quiz/quizzes/repositories/class.repository.ts
  packages/server/src/module/quiz/quizzes/repositories/quiz.repository.ts
Labels: 🤖 Refactor
