Repository boostcampwm-2024/web01-youQuiz, pull requests merged in 2024-11, with the labels that each got.

#55 [FE] - api 통신을 위한 apiClient 구현
  packages/FE/src/main.tsx
  packages/FE/src/shared/api/index.ts
  packages/FE/tsconfig.json
Labels: ✨ Feature

#65 [BE - #64] redis 연결 세팅
  .pnp.cjs
  .yarn/cache/@types-ioredis-npm-5.0.0-6efa70abfa-e52ce4239f.zip
  packages/server/package.json
  packages/server/src/app.module.ts
  packages/server/src/config/database/redis/redis.config.ts
  yarn.lock
Labels: ✨ Feature

#66 [BE] - redis 연결 오류 수정
  .pnp.cjs
  .yarnrc.yml
  packages/server/src/app.controller.ts
  packages/server/src/app.module.ts
  packages/server/src/app.service.ts
  packages/server/src/config/database/redis/redis.service.ts
  yarn.lock
Labels: 🛠️ Fix

#68 [BE - #67] - tslib 라이브러리 삭제 및 redis 연결 테스트
  .pnp.cjs
  Dockerfile.be
  packages/server/package.json
  yarn.lock
Labels: 🛠️ Fix

#69 [BE - #68] BE 도커 파일 수정
  .github/workflows/backend-ci-cd-test.yml
  .github/workflows/backend-ci-cd.yml
  Dockerfile.be
Labels: 🛠️ Fix

#70 [FE] - 페이지 네비게이션 및 퀴즈 리스트 페이지 생성
  packages/client/src/app/routes/Router.tsx
  packages/client/src/pages/nickname/index.tsx
  packages/client/src/pages/qna/index.tsx
  packages/client/src/pages/quiz-create/index.tsx
  packages/client/src/pages/quiz-list/index.tsx
  packages/client/src/pages/quiz-list/ui/QuizTitleModal.tsx
  packages/client/src/pages/quiz-question/index.tsx
  packages/client/src/pages/quiz-session/index.tsx
  packages/client/src/pages/quiz-session/ui/Quiz.tsx
  packages/client/src/pages/quiz-session/ui/QuizForm.tsx
  packages/client/src/pages/quiz-wait/index.tsx
  packages/client/src/shared/ui/modal/index.tsx
Labels: ✨ Feature

#78 [FE] - 빌드 에러 수정
  packages/client/src/pages/nickname/index.tsx
  packages/client/src/pages/quiz-wait/index.tsx
Labels: 🛠️ Fix

#81 [BE - #80 ] pinCode check API 구현
  packages/server/src/app.module.ts
  packages/server/src/module/game/game.gateway.ts
  packages/server/src/module/game/games/game.controller.ts
  packages/server/src/module/game/games/game.service.ts
Labels: ✨ Feature

#82 feature: make cors setting
  packages/server/src/main.ts
Labels: ✨ Feature

#84 [BE] - show quiz 이벤트 처리 구현
  packages/server/src/module/game/game.gateway.ts
  packages/server/src/module/game/games/game.service.ts
  packages/server/src/module/quiz/quizzes/repositories/class.repository.ts
Labels: ✨ Feature

#83 [FE - #73] 참여자 퀴즈 풀이 페이지 UI 구현 및 소켓 기능 구현
  packages/client/src/pages/quiz-session/index.tsx
  packages/client/src/pages/quiz-session/ui/Quiz.tsx
  packages/client/src/pages/quiz-session/ui/QuizBackground.tsx
  packages/client/src/pages/quiz-session/ui/QuizBox.tsx
  packages/client/src/pages/quiz-session/ui/QuizForm.tsx
  packages/client/src/pages/quiz-session/ui/QuizHeader.tsx
  packages/client/src/pages/quiz-session/ui/QuizLoading.tsx
  packages/client/src/shared/ui/header/Header.tsx
  packages/client/tailwind.config.js
Labels: ✨ Feature

#85 [FE] - 퀴즈 생성부터 퀴즈 실행 전 실시간 통신 구현
  packages/client/src/app/routes/Router.tsx
  packages/client/src/pages/main/index.tsx
  packages/client/src/pages/nickname/index.tsx
  packages/client/src/pages/quiz-list/index.tsx
  packages/client/src/pages/quiz-wait/index.tsx
  packages/client/src/shared/api/games/index.ts
  packages/client/src/shared/api/index.ts
  packages/client/src/shared/utils/socket.ts
  packages/client/src/shared/utils/waitForSocketEvent.ts
Labels: ✨ Feature

#87 [BE] - timeLimit 변수 인식 못하는 문제 해결
  packages/server/src/module/game/game.gateway.ts
Labels: 🛠️ Fix

#88 [FE] - 네비게이션, 렌더링 에러
  packages/client/src/app/routes/Router.tsx
  packages/client/src/pages/nickname/index.tsx
  packages/client/src/pages/quiz-list/index.tsx
  packages/client/src/pages/quiz-master-session/index.tsx
  packages/client/src/pages/quiz-wait/index.tsx
  packages/server/src/module/game/game.gateway.ts
Labels: 🛠️ Fix

#92 [FE] - 깃허브 액션 도커 빌드 수정
  .github/workflows/frontend-ci-cd.yml
Labels: 🛠️ Fix, 👷 Build

#94 [BE -#93] 캐싱된 퀴즈 확인 및 문제 개수 저장
  packages/server/src/config/database/redis/redis.service.ts
  packages/server/src/module/game/game.gateway.ts
Labels: ✨ Feature

#96 [BE] - sid의 master, participant 타입 구별 API 구현
  packages/server/src/module/game/game.gateway.ts
  packages/server/src/module/game/games/game.controller.ts
  packages/server/src/module/game/games/game.service.ts
Labels: ✨ Feature

#98 [FE] - 퀴즈 대기 페이지 UI 수정 및 작은 에러 수정
  packages/client/src/app/routes/Router.tsx
  packages/client/src/pages/quiz-list/index.tsx
  packages/client/src/pages/quiz-wait/index.tsx
  packages/client/src/shared/assets/icons/loading-alt-loop.svg
Labels: 🛠️ Fix, ✨ Feature

#101 [FE] - 린트 에러 수정
  packages/client/src/pages/quiz-wait/index.tsx
  packages/client/src/shared/api/index.ts
Labels: 🛠️ Fix

#97 [FE] - 퀴즈 진행 페이지 소켓 연결
  packages/client/src/pages/quiz-session/index.tsx
  packages/client/src/pages/quiz-session/type.d.ts
  packages/client/src/pages/quiz-session/ui/QuizBox.tsx
  packages/client/src/pages/quiz-session/ui/QuizEnd.tsx
  packages/client/src/pages/quiz-session/ui/QuizLoading.tsx
  packages/client/src/pages/quiz-wait/index.tsx
  packages/client/tailwind.config.js
Labels: ✨ Feature

#102 [BE - #]
  packages/server/src/module/game/game.gateway.ts
Labels: ✨ Feature

#103 [FE] - useGetUserType Query 구현
  packages/client/src/pages/quiz-wait/index.tsx
  packages/client/src/shared/hooks/useGetUserType.ts
Labels: ✨ Feature

#105 [공통] - 퀴즈 이벤트 추가
  packages/client/src/pages/quiz-master-session/index.tsx
  packages/client/src/pages/quiz-session/index.tsx
  packages/client/src/pages/quiz-session/ui/QuizBox.tsx
  packages/client/src/pages/quiz-wait/index.tsx
  packages/server/src/module/game/game.gateway.ts
Labels: 🛠️ Fix

#107 [BE -#106] 실시간 소켓 서버 송수신 데이터 인터페이스 정의
  packages/shared/interfaces/request/index.ts
  packages/shared/interfaces/request/master-entry.request.interface.ts
  packages/shared/interfaces/request/nickname.request.interface.ts
  packages/shared/interfaces/request/participant-entry.request.interface.ts
  packages/shared/interfaces/request/show-quiz.request.interface.ts
  packages/shared/interfaces/request/start-quiz.request.interface.ts
  packages/shared/interfaces/response/index.ts
  packages/shared/interfaces/response/master-statistics.response.interface.ts
  packages/shared/interfaces/response/nickname.response.interface.ts
  packages/shared/interfaces/response/participant-statistics.response.interface.ts
  packages/shared/interfaces/response/pincode.response.interface.ts
  packages/shared/interfaces/response/session.response.interface.ts
  packages/shared/interfaces/response/show-quiz.response.interface.ts
  packages/shared/interfaces/response/start-quiz.response.interface.ts
  packages/shared/interfaces/response/submit-answer.request.interface.ts
  packages/shared/interfaces/response/time-end.response.interface.ts
  packages/shared/interfaces/response/timer-tick.response.interface.ts
  packages/shared/interfaces/utils/choice.interface.ts
  packages/shared/interfaces/utils/quizdata.interface.ts
  packages/shared/types/a.ts
  packages/shared/types/quiz.types.ts
Labels: ✨ Feature

#110 [FE - #109 ] Quiz-Session 소켓 연결 및 리팩토링
  packages/client/src/pages/quiz-session/index.tsx
  packages/client/src/pages/quiz-session/ui/QuizBox.tsx
  packages/client/src/pages/quiz-session/ui/QuizHeader.tsx
  packages/client/src/pages/quiz-session/ui/QuizLoading.tsx
  packages/client/tailwind.config.js
Labels: ✨ Feature, 🤖 Refactor

#113 [BE - #112] - 이모지 이벤트 추가 및 총 제출 수 이벤트 추가
  packages/server/src/module/game/game.gateway.ts
  packages/shared/interfaces/request/emoji.request.interface.ts
  packages/shared/interfaces/request/index.ts
  packages/shared/interfaces/response/emoji.response.interface.ts
  packages/shared/interfaces/response/master-statistics.response.interface.ts
  packages/shared/types/emoji.types.ts
Labels: ✨ Feature

#114 [FE] - 퀴즈 진행 마스터 페이지 소켓 이벤트 추가
  packages/client/src/pages/quiz-list/index.tsx
  packages/client/src/pages/quiz-master-session/index.tsx
  packages/client/src/pages/quiz-master-session/ui/AnswerChart.tsx
  packages/client/src/pages/quiz-master-session/ui/RecentSubmittedAnswers.tsx
  packages/client/src/pages/quiz-master-session/ui/StatisticsCard.tsx
  packages/client/src/pages/quiz-master-session/ui/StatisticsGroup.tsx
  packages/client/src/pages/quiz-session/ui/QuizBox.tsx
  packages/client/src/shared/utils/socket.ts
Labels: ✨ Feature

#116 [FE] - 퀴즈 세션 페이지
  packages/client/src/pages/quiz-master-session/index.tsx
  packages/client/src/pages/quiz-master-session/ui/RecentSubmittedAnswers.tsx
  packages/client/src/pages/quiz-master-session/ui/StatisticsGroup.tsx
  packages/client/src/pages/quiz-session/index.tsx
  packages/client/src/pages/quiz-session/type.d.ts
  packages/client/src/pages/quiz-session/ui/AfterQuizSubmit.tsx
  packages/client/src/pages/quiz-session/ui/QuizBox.tsx
  packages/client/src/pages/quiz-session/ui/QuizHeader.tsx
  packages/client/src/pages/quiz-wait/index.tsx
  packages/client/src/shared/hooks/useSocket.ts
Labels: ✨ Feature

#118 [BE-#117] 실시간 소켓 서버 DTO 생성 및 shared연결
  packages/server/src/module/game/games/dto/emoji.request.dto.ts
  packages/server/src/module/game/games/dto/master-entry.request.dto.ts
  packages/server/src/module/game/games/dto/nickname.request.dto.ts
  packages/server/src/module/game/games/dto/participant-entry.request.dto.ts
  packages/server/src/module/game/games/dto/show-quiz.request.dto.ts
  packages/server/src/module/game/games/dto/start-quiz.request.dto.ts
  packages/server/src/module/quiz/quizzes/dto/class.response.dto.ts
  packages/server/src/module/quiz/quizzes/quiz.controller.ts
  packages/server/src/module/quiz/quizzes/quiz.service.ts
  packages/server/tsconfig.json
Labels: ✨ Feature

#120 [BE] - sid, socketId 맵핑 추가, 통계 자료 오류 및 currentOrder 갱신 위치 변경
  packages/server/src/module/game/game.gateway.ts
Labels: 🛠️ Fix, ✨ Feature

#127 [BE-#125 #126] 퀴즈 관련 도메인 반환 값 추가 GET API 구현
  packages/server/src/module/quiz/quizzes/dto/choice.response.dto.ts
  packages/server/src/module/quiz/quizzes/dto/create-class.response.dto.ts
  packages/server/src/module/quiz/quizzes/dto/quiz.response.dto.ts
  packages/server/src/module/quiz/quizzes/quiz.controller.ts
  packages/server/src/module/quiz/quizzes/quiz.service.ts
  packages/server/src/module/quiz/quizzes/repositories/quiz.repository.ts
  packages/shared/interfaces/response/choice.response.interface.ts
  packages/shared/interfaces/response/quiz.response.interface.ts
Labels: ✨ Feature

#124 [FE] - 메인 페이지 및 API 연결
  packages/client/src/app/layouts/HostLayout.tsx
  packages/client/src/app/routes/Router.tsx
  packages/client/src/pages/main/index.tsx
  packages/client/src/pages/main/ui/FloatingQuestion.tsx
  packages/client/src/pages/main/ui/FloatingSquare.tsx
  packages/client/src/pages/quiz-create/index.tsx
  packages/client/src/pages/quiz-create/ui/AnswerBox.tsx
  packages/client/src/pages/quiz-create/ui/QuizCreateSection.tsx
  packages/client/src/pages/quiz-list/index.tsx
  packages/client/src/pages/quiz-list/ui/QuizTitleModal.tsx
  packages/client/src/pages/quiz-master-session/index.tsx
  packages/client/src/pages/quiz-session/ui/QuizBox.tsx
  packages/client/src/shared/api/classes/index.ts
  packages/client/src/shared/api/index.ts
  packages/client/src/shared/api/quizzes/index.ts
  packages/client/src/shared/assets/icons/circle-message.svg
  packages/client/src/shared/constants/initialState.ts
  packages/client/src/shared/hooks/classes.ts
  packages/client/src/shared/hooks/quizzes.ts
  packages/client/src/shared/ui/header/Header.tsx
  packages/client/src/shared/ui/input-box/InputBox.tsx
  packages/client/tailwind.config.js
  packages/shared/interfaces/response/timer-tick.response.interface.ts
Labels: 🛠️ Fix, ✨ Feature

#129 [BE - #128 ] show ranking 이벤트 구현
  .yarn/cache/ioredis-npm-5.4.1-c96e18ae67-5d28b7c89a.zip
  packages/server/src/config/database/redis/redis.service.ts
  packages/server/src/module/game/game.gateway.ts
  packages/server/src/module/game/games/game.service.ts
Labels: ✨ Feature

#131 [FE] - 퀴즈 종료 시 라우팅 추가 및 퀴즈 랭킹 정보 소켓 연결
  packages/client/src/app/routes/Router.tsx
  packages/client/src/pages/leaderboard/index.tsx
  packages/client/src/pages/quiz-master-session/index.tsx
  packages/client/src/pages/quiz-session/index.tsx
  packages/client/src/pages/quiz-session/ui/AfterQuizSubmit.tsx
  packages/client/src/pages/quiz-session/ui/QuizBox.tsx
  packages/client/src/pages/quiz-session/ui/QuizEnd.tsx
Labels: ✨ Feature

#132 [BE -] 리더보드 레디스 데이터 참가자 참여 시 추가
  packages/server/src/module/game/game.gateway.ts
Labels: ✨ Feature

#135 [FE] - 클래스, 퀴즈 생성 페이지 에러 해결
  packages/client/src/pages/quiz-create/index.tsx
  packages/client/src/pages/quiz-create/ui/QuizCreateSection.tsx
  packages/client/src/pages/quiz-list/index.tsx
  packages/client/src/pages/quiz-list/ui/ClassItem.tsx
  packages/client/src/pages/quiz-list/ui/QuizTitleModal.tsx
  packages/client/src/pages/quiz-master-session/index.tsx
  packages/client/src/pages/quiz-master-session/ui/EmojiChart.tsx
  packages/client/src/pages/quiz-master-session/ui/StatisticsGroup.tsx
  packages/client/src/shared/api/classes/index.ts
  packages/client/src/shared/assets/icons/bin.svg
  packages/client/src/shared/hooks/classes.ts
Labels: 🛠️ Fix, ✨ Feature

#137 [BE - #136 ] time sync 관련 오류 및 nickname 이벤트 로직 수정
  packages/server/src/app.controller.ts
  packages/server/src/app.module.ts
  packages/server/src/app.service.ts
  packages/server/src/config/database/mysql/configuration.module.ts
  packages/server/src/config/database/redis/redis.module.ts
  packages/server/src/module/game/game.gateway.spec.ts
  packages/server/src/module/game/game.module.ts
  packages/server/src/module/game/games/game.gateway.ts
  packages/server/src/module/game/games/game.service.ts
  packages/shared/types/connection.types.ts
  packages/shared/types/gameStatus.types.ts
Labels: 🤖 Refactor

#138 [공통] - 채팅 기능 구현
  packages/client/src/pages/quiz-wait/index.tsx
  packages/client/src/pages/quiz-wait/ui/UserGridItem.tsx
  packages/client/src/pages/quiz-wait/ui/UserGridView.tsx
  packages/client/src/shared/assets/characters/햄스터.png
  packages/server/src/module/game/games/game.gateway.ts
Labels: ✨ Feature

#143 [FE] - API 응답값 변경에 대한 API 구조 변경
  packages/client/src/app/routes/Router.tsx
  packages/client/src/pages/quiz-list/index.lazy.tsx
  packages/client/src/pages/quiz-list/index.tsx
  packages/client/src/pages/quiz-list/ui/ClassItem.tsx
  packages/client/src/pages/quiz-list/ui/QuizTitleModal.tsx
  packages/client/src/shared/api/classes/index.ts
  packages/client/src/shared/boundary/AsyncBoundary.tsx
  packages/client/src/shared/hooks/classes.ts
Labels: ✨ Feature
